name: linux-build-dist
on: [push, pull_request]
env:
  GSL_VERSION: 2.6
jobs:
  build-dist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set environment
        run: |
          echo "GSL_INST_DIR=${GITHUB_WORKSPACE}/gsl" >> $GITHUB_ENV
          echo "GSL_SRC_DIR=${GITHUB_WORKSPACE}/gsl-source" >> $GITHUB_ENV
      - name: install perl
        run: |
          # NOTE: The following packages are already installed in "ubuntu-20.04" :
          #     build-essential curl g++ git wget libssl-dev libz-dev
          # NOTE: PWD=/home/runner/work/math--gsl--gha/math--gsl--gha
          # NOTE: perl version 5.26.1 is already installed (on Ubuntu 20.04),
          #   but we would like to not mess with that, so we install a custom perl.
          ./.github/scripts/install_perl.sh
      - name: show perl info
        run: |
          perl --version
          export PATH=$GITHUB_WORKSPACE/perl/bin:$PATH
          echo "PATH=$PATH" >> $GITHUB_ENV
          perl --version
          cpan -v
          uname -a
          lsb_release -d
      - name: install gsl
        run: |
          ./.github/scripts/install_gsl.sh
      - name: install perl modules
        run: |
          export LD_LIBRARY_PATH="$GSL_INST_DIR"/"$TARBALL_GSL"/lib
          export PATH="$GSL_INST_DIR"/"$TARBALL_GSL"/bin:"$PATH"
          cpan App::cpanminus
          cpanm -n Net::SSLeay
          cpanm Alien::GSL
          cpanm Module::Build
          perl Build.PL
          ./Build installdeps --cpan_client cpanm
          ./Build
          ./Build test
          ./Build dist
          #DISTNAME=$(ls -1 Math*.tar.gz)
          DISTNAME=Math-GSL
          #echo "MATH_GSL_DISTNAME=$DISTNAME" >> $GITHUB_ENV
        - name: Save dist as artifact
          uses: actions/upload-artifact@v2
          with:
            name: math_gsl_dist_name
            path: ${{ env.MATH_GSL_DISTNAME }}
            
