name: linux-build-dist
on: [push, pull_request]
jobs:
  build-dist:
    runs-on: ubuntu-20.04
    env:
      GSL_VERSION: 2.6
    steps:
      - uses: actions/checkout@v2
      - name: set environment variables
        run: ./.github/scripts/set_environment_variables.sh
      - name: install packages
        run: |
          sudo apt-get install swig autoconf libtool
          swig -version
      - name: install perl
        run: |
          # NOTE: The following packages are already installed in "ubuntu-20.04" :
          #     build-essential curl g++ git wget libssl-dev libz-dev
          #       swig autoconf libtool
          # NOTE: PWD=/home/runner/work/math--gsl--gha/math--gsl--gha
          # NOTE: perl version 5.26.1 is already installed (on Ubuntu 20.04),
          #   but we would like to not mess with that, so we install a custom perl.
          ./.github/scripts/install_perl.sh
      - name: show perl info
        run: |
          ./.github/scripts/show_perl_info.sh
      - name: install gsl
        run: |
          ./.github/scripts/install_gsl.sh
      - name: install perl modules and build dist
        run: |
          ./.github/scripts/build_dist.sh
      - name: Save dist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: math_gsl_dist
          path: ${{ env.MATH_GSL_DISTNAME }}
      - name: Save name of dist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: math_gsl_dist_name
          path: math-gsl-dist-name.txt
  install-dist-linux:
    runs-on: ubuntu-20.04
    needs: build-dist
    env:
      GSL_VERSION: 2.6
    steps:
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: math_gsl_dist
      - name: Download dist name
        uses: actions/download-artifact@v2
        with:
          name: math_gsl_dist_name
      - name: set environment variables
        run: ./.github/scripts/set_environment_variables.sh
      - name: install gsl
        run: ./.github/scripts/install_gsl.sh
      - name: Build module
        run: |
          DISTNAME=$(<math-gsl-dist-name.txt)
          tar zxvf $DISTNAME
          DISTDIR=$(perl -pe 's/\.tar.gz$//' <<<"$DISTNAME")
          cd $DISTDIR
          perl Build.PL
          ./Build
          ./Build test
