name: linux-build-dist
on: [push, pull_request]
jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        shell: bash
        run: |
          #sudo apt-get install -y build-essential curl g++ git wget libssl-dev libz-dev
          wget https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
          tar zxvf perl-5.32.0.tar.gz
          #PWD=/home/runner/work/math--gsl--gha/math--gsl--gha
          cd perl-5.32.0
          sh Configure -des -Dprefix=$GITHUB_WORKSPACE/perl -Dman1dir=none -Dman3dir=none
          make
          make install
          perl --version
          export PATH=$GITHUB_WORKSPACE/perl/bin:$PATH
          perl --version
