name: linux-build-dist
on: [push, pull_request]
jobs:
  build-dist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install perl
        run: |
          # NOTE: The following packages are already installed in "ubuntu-latest"
          #sudo apt-get install -y build-essential curl g++ git wget libssl-dev libz-dev
          # NOTE: PWD=/home/runner/work/math--gsl--gha/math--gsl--gha
          # NOTE: perl version 5.26.1 is already installed (on Ubuntu 20.04),
          #   but we would like to not mess with that, so we install a custom perl.
          ./.github/scripts/install_perl.sh
      - name: show perl info
        run: |
          export PATH=$GITHUB_WORKSPACE/perl/bin:$PATH
          perl --version
          uname -a
          lsb_release -d
      - name: install gsl
        run: |
          ./.github/scripts/install_gsl.sh
